### ISSUE TITLE
firefox-kde-opensuse missbehaves on Latte dock

### ISSUE THREAD

**Issue by michaldybczak** [Thaodan/thaopkgs#1] opened 2019-08-01 16:54 UTC
Sorry if that is not the right place to post this issue but I couldn't find a more proper place.

I started to have problems after 68.0.1-1 update.

FF shows as a TXT file icon on the right end, when turned on it switches back to FF icon.

![Screenshot-2019-08-01-18-12-13](https://user-images.githubusercontent.com/10132958/62311743-c54ba180-b48c-11e9-8e5e-0710dac7b80e.png)

I tried to unpin it and pin it again, the same result. It worked fine till the latest update.

After some experiments:

1. After downgrading FF to the previous firefox-kde-opensuse version 68.0.0-2 issue stops and FF behaves normally on the Latte dock.
After updating it starts to show this bizarre behavior again, namely, when I click on the launcher, it opens another FF icon instance (so I have two FF icons). When I disable it and try to pin again, I get the same problem as described above.
2. Regular FF doesn't have this problem. ALso Plasmafox (basically firefox-kde-opensuse version made by torvic) works correctly in 68.0.1

Looks like firefox-kde opensuse 68.0.1-1 is somehow broken and thus cannot behave correctly on a dock.

latte-dock uses libtaskmanager so anything that works correctly with it should work the same way with latte. Since it doesn't, I assume this is kind of a specific bug of this version or compilation.

**Comment by Thaodan** [comment] 2019-08-01 18:35
Its better to report at gitlab (see the aur page)
No idea what could be wrong . You could try if you 
build it yourself if it has the same issue (just disable 
pgo for the try).

But first I'd try a fresh user profile.

**Comment by michaldybczak** [comment] 2019-08-01 19:44
I'll wait for the next release and hopefully, it will work fine as before. As to gitlab, frankly speaking, I hate it and I will not use it. There is one account for Github while I need to spawn new accounts each time I want to participate in Gitlab projects. This is a mess for password managers because they treat it as one site. This is ridiculous and I'm shocked people use it.

Thanks for responding here thou. If the next release will have the same problem I will try to build it to see if it made any difference but on the long run, I use your repo for not having to compile it myself. It's enough I have to compile thunderbird-appmenu.

New FF releases are coming regularly and often so I'll wait patiently.

Thanks for the awesome repo. I'll report back if something has changed.

**Comment by michaldybczak** [comment] 2019-08-02 19:48
OK, I found the solution thanks to Latte's developer who knew the answer:

https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

I had to change:

`StartupWMClass=firefox`

to

`StartupWMClass=firefox-kde-opensuse`

in `/usr/share/applications/firefox.desktop`

So I'm not sure if the latest **firefox-kde-opensuse** forgot to update that desktop file or somehow changed the names somewhere that required also to change in .desktop file? Anyway, I thought you may want to know and possibly fix it in the next release.

**Comment by Thaodan** [comment] 2019-08-02 20:20
I'll look into it at the next release. thanks for investigating.

**Comment by Thaodan** [comment] 2019-08-12 21:40
Should be fixed by https://github.com/Thaodan/thaopkgs/commit/f7c76e1e8d244482fcd2d59424d0cc0bf8158947
If the issue is occurs again please reopen.

**Closed as completed by Thaodan** 2019-08-12 21:40 UTC
